name: WanaIQ Progress Tracking

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at 9 AM EAT (6 AM UTC)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  track-progress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for accurate metrics

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run progress tracker
        id: tracker
        run: |
          node progress_tracker.js report > progress_output.txt
          cat progress_output.txt

      - name: Calculate code metrics
        id: metrics
        run: |
          # Line count
          TOTAL_LINES=$(find src -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}' || echo "0")
          echo "total_lines=$TOTAL_LINES" >> $GITHUB_OUTPUT
          
          # Test coverage
          npm run test:coverage -- --silent 2>&1 > coverage_output.txt || true
          COVERAGE=$(grep "All files" coverage_output.txt | awk '{print $10}' | tr -d '%' || echo "0")
          echo "test_coverage=$COVERAGE" >> $GITHUB_OUTPUT
          
          # TypeScript percentage
          TS_FILES=$(find src -name "*.ts" -o -name "*.tsx" 2>/dev/null | wc -l || echo "0")
          JS_FILES=$(find src -name "*.js" -o -name "*.jsx" 2>/dev/null | wc -l || echo "0")
          TOTAL_FILES=$((TS_FILES + JS_FILES))
          if [ $TOTAL_FILES -gt 0 ]; then
            TS_PERCENT=$((TS_FILES * 100 / TOTAL_FILES))
          else
            TS_PERCENT=0
          fi
          echo "typescript_percent=$TS_PERCENT" >> $GITHUB_OUTPUT

      - name: Scan technical debt
        id: debt
        run: |
          # Count debt items by category
          DEBT_SECURITY=$(grep -r "TODO: \[DEBT-SECURITY\]" src/ 2>/dev/null | wc -l || echo "0")
          DEBT_PERF=$(grep -r "TODO: \[DEBT-PERF\]" src/ 2>/dev/null | wc -l || echo "0")
          DEBT_UX=$(grep -r "TODO: \[DEBT-UX\]" src/ 2>/dev/null | wc -l || echo "0")
          
          echo "security=$DEBT_SECURITY" >> $GITHUB_OUTPUT
          echo "perf=$DEBT_PERF" >> $GITHUB_OUTPUT
          echo "ux=$DEBT_UX" >> $GITHUB_OUTPUT

      - name: Run Lighthouse CI (if web app exists)
        id: lighthouse
        continue-on-error: true
        run: |
          if [ -f "lighthouserc.json" ]; then
            npm install -g @lhci/cli
            lhci autorun
          else
            echo "Lighthouse config not found, skipping..."
          fi

      - name: Create progress badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: your-gist-id-here  # Create a gist and add ID
          filename: wanaiq-progress.json
          label: Progress
          message: ${{ steps.tracker.outputs.overall_progress }}%
          color: |
            ${{ steps.tracker.outputs.overall_progress >= 80 && 'green' || 
                steps.tracker.outputs.overall_progress >= 60 && 'yellow' || 
                steps.tracker.outputs.overall_progress >= 40 && 'orange' || 'red' }}

      - name: Create test coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: your-gist-id-here
          filename: wanaiq-coverage.json
          label: Coverage
          message: ${{ steps.metrics.outputs.test_coverage }}%
          color: |
            ${{ steps.metrics.outputs.test_coverage >= 80 && 'green' || 
                steps.metrics.outputs.test_coverage >= 60 && 'yellow' || 'red' }}

      - name: Comment PR with progress
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('progress_output.txt', 'utf8');
            
            const comment = `## 📊 WanaIQ Progress Report
            
            ${output}
            
            ### 📈 Code Metrics
            - **Total Lines:** ${{ steps.metrics.outputs.total_lines }}
            - **Test Coverage:** ${{ steps.metrics.outputs.test_coverage }}%
            - **TypeScript:** ${{ steps.metrics.outputs.typescript_percent }}%
            
            ### 🔧 Technical Debt
            - **Critical (Security):** ${{ steps.debt.outputs.security }} 🚨
            - **High (Performance):** ${{ steps.debt.outputs.perf }}
            - **High (UX):** ${{ steps.debt.outputs.ux }}
            
            ---
            *Auto-generated by WanaIQ Progress Tracker*
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Upload progress report artifact
        uses: actions/upload-artifact@v3
        with:
          name: progress-report-${{ github.sha }}
          path: |
            progress_output.txt
            reports/

      - name: Send Slack notification (if configured)
        if: github.event_name == 'schedule' && steps.debt.outputs.security > 0
        uses: slackapi/slack-github-action@v1.24.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "🚨 WanaIQ Alert: ${{ steps.debt.outputs.security }} critical security debt items detected!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*WanaIQ Security Alert*\n\nCritical technical debt detected:\n• Security: ${{ steps.debt.outputs.security }} items\n• Performance: ${{ steps.debt.outputs.perf }} items\n\nAction required before milestone completion."
                  }
                }
              ]
            }

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run npm audit
        run: |
          npm audit --audit-level=moderate || true

  performance-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Bundle size check
        run: |
          BUNDLE_SIZE=$(du -sk dist/ | awk '{print $1}')
          MAX_SIZE=200  # 200KB maximum for initial bundle
          
          echo "Bundle size: ${BUNDLE_SIZE}KB"
          
          if [ $BUNDLE_SIZE -gt $MAX_SIZE ]; then
            echo "❌ Bundle size exceeds ${MAX_SIZE}KB limit!"
            exit 1
          else
            echo "✅ Bundle size within limits"
          fi
