import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface GovernmentInstitution {
  id: string;
  name: string;
  acronym: string | null;
  institution_type: string;
  jurisdiction_type: string;
  jurisdiction_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  physical_address: string | null;
  website: string | null;
}

interface RoutingResult {
  institution_id: string | null;
  institution_name: string;
  institution_acronym: string | null;
  institution_type: string;
  institution_website: string | null;
  institution_email: string | null;
  institution_phone: string | null;
  institution_address: string | null;
  issue_type: string;
  department_slug: string;
  jurisdiction: string;
  severity: number;
  confidence: number;
  recommended_actions: string[];
  formal_letter: string;
  processing_time_ms: number;
}

function normalizeLocation(location: unknown): string | null {
  if (!location) return null;

  if (typeof location === "string") {
    const trimmed = location.trim();
    return trimmed.length > 0 ? trimmed : null;
  }

  if (typeof location === "object") {
    const loc = location as Record<string, unknown>;
    const parts = [loc.text, loc.ward, loc.constituency, loc.county]
      .filter((value): value is string => typeof value === "string" && value.trim().length > 0)
      .map((value) => value.trim());

    if (parts.length > 0) {
      return parts.join(", ");
    }
  }

  return null;
}

function buildFallbackLetter(
  issueDescription: string,
  location: unknown,
  institutionName: string,
  institutionAcronym: string | null,
  institutionAddress: string | null,
  recommendedActions: string[],
  severity: number
): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-KE", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const refNum = `WC/${now.getFullYear()}/${Math.floor(Math.random() * 90000) + 10000}`;
  const acronym = institutionAcronym ? `(${institutionAcronym})` : "";
  const locationText = normalizeLocation(location);
  const actions = recommendedActions.length > 0
    ? recommendedActions.map((a, i) => `${i + 1}. ${a}`).join("\n")
    : "1. Conduct an immediate inspection of the reported issue\n2. Provide a written response with a timeline for resolution";

  return `REF: ${refNum}
Date: ${dateStr}

The ${institutionName} ${acronym}
${institutionAddress || "[Institution Address]"}

Dear Sir/Madam,

RE: FORMAL COMPLAINT — CIVIC ISSUE REPORT ${locationText ? `(${locationText.toUpperCase()})` : ""}

I write to formally bring to your attention a civic matter of ${severity >= 7 ? "critical urgency" : severity >= 4 ? "significant concern" : "concern"} that requires your office's immediate attention.

The issue pertains to: ${issueDescription}

${locationText ? `The matter is located at/in ${locationText} and directly affects residents of the jurisdiction under your mandate.` : "The matter directly affects residents under your jurisdiction."}

I respectfully request that your office:
${actions}

I trust this matter will be accorded the urgency it deserves. Kindly acknowledge receipt of this complaint and provide a timeline for resolution.

Yours faithfully,

[Complainant Name]
[Contact Information]
[Date]

---
This letter was generated by the WanaIQ Civic Engagement Platform.
Reference: ${refNum}`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const groqApiKey = Deno.env.get("GROQ_API_KEY");

    if (!groqApiKey) {
      return new Response(JSON.stringify({ error: "GROQ_API_KEY not configured" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Auth validation
    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: { user }, error: authError } = await supabase.auth.getUser(
      authHeader.replace("Bearer ", "")
    );
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Invalid token" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const userId = user.id;

    const body = await req.json();
    const issue_description = body?.issue_description;
    const locationText = normalizeLocation(body?.location);

    if (!issue_description) {
      return new Response(JSON.stringify({ error: "issue_description is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (typeof issue_description !== "string" || issue_description.length > 5000) {
      return new Response(JSON.stringify({ error: "issue_description must be under 5000 chars" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const startTime = Date.now();
    const serviceClient = createClient(supabaseUrl, supabaseServiceKey);

    // STEP 1: Fetch real government institutions from DB (limit to 40 to stay within Groq TPM)
    const { data: institutions, error: institutionsError } = await serviceClient
      .from("government_institutions")
      .select("id, name, acronym, institution_type, jurisdiction_type, jurisdiction_name, contact_email, contact_phone, physical_address, website")
      .eq("is_active", true)
      .eq("country_code", "KE")
      .order("institution_type")
      .limit(40);

    if (institutionsError) {
      console.error("Failed to fetch institutions:", institutionsError.message);
    }

    const institutionList: GovernmentInstitution[] = institutions || [];

    // Build compact institution context for Groq
    const institutionContext = institutionList.length > 0
      ? institutionList.map((inst) =>
          `- ${inst.id}|${inst.name}${inst.acronym ? ` (${inst.acronym})` : ""}|${inst.institution_type}|${inst.jurisdiction_type}`
        ).join("\n")
      : "No institutions available — use best judgment based on the issue type.";

    // STEP 2: First Groq call — route issue to real institution
    const routingSystemPrompt = `You are a civic issue routing AI for Kenya. Given a citizen's issue, match it to the MOST APPROPRIATE institution from the provided list.

AVAILABLE GOVERNMENT INSTITUTIONS (use EXACTLY one of these):
${institutionContext}

ROUTING RULES:
- Water/sewerage issues → prefer county water company (WSP) if county is known, else Ministry of Water
- Roads → KeNHA for national highways, KURA for urban roads, county government for county roads
- Electricity → Kenya Power (KPLC)
- Health → county government health dept or Ministry of Health for national issues
- Land → National Land Commission or Ministry of Lands
- Environment → NEMA or Ministry of Environment
- Education → Ministry of Education for national, county government for pre-primary
- Always prefer the most specific/local institution over a national one when location context is available

Respond ONLY with valid JSON — no extra text:
{
  "institution_id": "UUID from the list above or null if no match",
  "institution_name": "exact name from list or best fallback name",
  "institution_acronym": "acronym or null",
  "issue_type": "water|roads|health|education|security|land|agriculture|environment|energy|administration|other",
  "department_slug": "kebab-case",
  "jurisdiction": "national|county|constituency|ward",
  "severity": 1-10,
  "confidence": 0.0-1.0,
  "recommended_actions": ["action1", "action2", "action3"]
}`;

    const routingResponse = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${groqApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "llama-3.1-8b-instant",
        messages: [
          { role: "system", content: routingSystemPrompt },
          {
            role: "user",
            content: `Issue: ${issue_description}${locationText ? `\nLocation: ${locationText}` : ""}`,
          },
        ],
        temperature: 0.1,
        max_tokens: 600,
        response_format: { type: "json_object" },
      }),
    });

    if (!routingResponse.ok) {
      const errBody = await routingResponse.text();
      throw new Error(`Groq routing API error [${routingResponse.status}]: ${errBody}`);
    }

    const routingData = await routingResponse.json();
    const rawContent = routingData.choices?.[0]?.message?.content || "{}";
    let routingResult: Record<string, unknown>;
    try {
      routingResult = JSON.parse(rawContent);
    } catch {
      routingResult = {};
    }

    // Resolve the matched institution from DB for accurate details
    const matchedInstitutionId = routingResult.institution_id as string | null;
    let matchedInstitution: GovernmentInstitution | null = null;

    if (matchedInstitutionId) {
      matchedInstitution = institutionList.find((i) => i.id === matchedInstitutionId) || null;
    }

    // Fallback: if AI returned a name but not a valid ID, try name match
    if (!matchedInstitution && routingResult.institution_name) {
      const aiName = (routingResult.institution_name as string).toLowerCase();
      matchedInstitution = institutionList.find((i) =>
        i.name.toLowerCase().includes(aiName) || aiName.includes(i.name.toLowerCase())
      ) || null;
    }

    const institutionName = matchedInstitution?.name || (routingResult.institution_name as string) || "Relevant Government Authority";
    const institutionAcronym = matchedInstitution?.acronym || (routingResult.institution_acronym as string | null) || null;
    const recommendedActions = (routingResult.recommended_actions as string[]) || [];
    const severity = Number(routingResult.severity) || 5;

    // STEP 3: Second Groq call — generate formal Kenyan complaint letter
    const now = new Date();
    const dateStr = now.toLocaleDateString("en-KE", { day: "numeric", month: "long", year: "numeric" });
    const refNum = `WC/${now.getFullYear()}/${Math.floor(Math.random() * 90000) + 10000}`;

    const letterSystemPrompt = `You are drafting a formal complaint letter to a Kenyan government institution on behalf of a citizen.

Use this EXACT structure — no markdown, no headers, just plain text:

REF: ${refNum}
Date: ${dateStr}

The [Full Title of Head],
${institutionName}${institutionAcronym ? ` (${institutionAcronym})` : ""}
${matchedInstitution?.physical_address || "[Institution Address]"}

Dear Sir/Madam,

RE: FORMAL COMPLAINT — [SUBJECT IN CAPS]

[Opening paragraph: formally state the purpose of writing, the nature of the issue, and the location if provided]

[Second paragraph: describe the specific impact on residents/community, any health/safety risks, estimated duration of the problem]

[Third paragraph: formally request specific actions with urgency proportional to severity ${severity}/10. Reference the institution's mandate. Be firm but respectful]

I trust this matter will be accorded the urgency it deserves. Kindly acknowledge receipt of this complaint within 7 working days and provide a timeline for resolution under Article 35 of the Constitution of Kenya 2010.

Yours faithfully,

[Complainant Name]
[County], Kenya
[Date]

---
Reference: ${refNum} | Generated via WanaIQ Civic Platform`;

    let formalLetter: string;
    try {
      const letterResponse = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${groqApiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "llama-3.1-70b-versatile",
          messages: [
            { role: "system", content: letterSystemPrompt },
            {
              role: "user",
              content: `Write the formal complaint letter for this issue:
Issue: ${issue_description}
${locationText ? `Location: ${locationText}` : ""}
Severity: ${severity}/10
Recommended actions: ${recommendedActions.join(", ")}
Addressed to: ${institutionName}${matchedInstitution?.physical_address ? `, ${matchedInstitution.physical_address}` : ""}`,
            },
          ],
          temperature: 0.3,
          max_tokens: 900,
        }),
      });

      if (letterResponse.ok) {
        const letterData = await letterResponse.json();
        formalLetter = letterData.choices?.[0]?.message?.content?.trim() || "";
      } else {
        console.warn("Letter generation failed, using fallback");
        formalLetter = "";
      }
    } catch (letterErr) {
      console.warn("Letter generation error:", letterErr);
      formalLetter = "";
    }

    // Fallback letter if AI generation fails
    if (!formalLetter) {
      formalLetter = buildFallbackLetter(
        issue_description,
        locationText,
        institutionName,
        institutionAcronym,
        matchedInstitution?.physical_address || null,
        recommendedActions,
        severity
      );
    }

    const processingTime = Date.now() - startTime;

    // STEP 4: Log to routing_logs
    await serviceClient.from("routing_logs").insert({
      user_id: userId,
      issue_description: issue_description.substring(0, 500),
      location: locationText,
      issue_type: routingResult.issue_type || null,
      department_slug: routingResult.department_slug || null,
      department_name: institutionName,
      severity,
      confidence: routingResult.confidence || null,
      recommended_actions: recommendedActions,
      model_used: "llama-3.1-8b-instant",
      processing_time_ms: processingTime,
    }).then(({ error }) => {
      if (error) console.warn("routing_logs insert failed:", error.message);
    });

    const result: RoutingResult = {
      institution_id: matchedInstitution?.id || null,
      institution_name: institutionName,
      institution_acronym: institutionAcronym,
      institution_type: matchedInstitution?.institution_type || (routingResult.issue_type as string) || "unknown",
      institution_website: matchedInstitution?.website || null,
      institution_email: matchedInstitution?.contact_email || null,
      institution_phone: matchedInstitution?.contact_phone || null,
      institution_address: matchedInstitution?.physical_address || null,
      issue_type: (routingResult.issue_type as string) || "other",
      department_slug: (routingResult.department_slug as string) || "unknown",
      jurisdiction: (routingResult.jurisdiction as string) || "county",
      severity,
      confidence: Number(routingResult.confidence) || 0.5,
      recommended_actions: recommendedActions,
      formal_letter: formalLetter,
      processing_time_ms: processingTime,
    };

    return new Response(JSON.stringify(result), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    console.error("civic-router error:", message);
    return new Response(
      JSON.stringify({ error: "An internal error occurred. Please try again later." }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
