// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.57.4";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return {
      content: [{ type: "text", text: "Not authenticated." }],
      isError: true
    };
  }
  return null;
}
function errorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}
function jsonResult(data, summary) {
  return {
    content: [
      { type: "text", text: summary ?? JSON.stringify(data) }
    ],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in WanaIQ user's profile (username, display name, county, constituency, ward, karma).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("profiles").select(
      "id, username, display_name, bio, avatar_url, county, constituency, ward, location, karma, post_karma, comment_karma, is_verified, role, onboarding_completed, created_at"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Profile not found.");
    return jsonResult(
      data,
      `${data.display_name ?? data.username ?? "user"} (u/${data.username ?? "unknown"}) \u2014 ${data.county ?? "no county"}${data.constituency ? `, ${data.constituency}` : ""}${data.ward ? `, ${data.ward}` : ""}`
    );
  }
});

// src/lib/mcp/tools/search-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var search_posts_default = defineTool2({
  name: "search_posts",
  title: "Search posts",
  description: "Search WanaIQ posts by keyword across title and content. Returns up to 20 results the signed-in user can read.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Search keywords (matched against title and content)."),
    limit: z.number().int().min(1).max(20).optional().describe("Max results (1-20, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const term = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await sb.from("posts").select(
      "id, title, content, author_id, community_id, upvotes, downvotes, comment_count, created_at, tags"
    ).or(`title.ilike.${term},content.ilike.${term}`).eq("is_hidden", false).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], `Found ${data?.length ?? 0} post(s) for "${query}".`);
  }
});

// src/lib/mcp/tools/get-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_post_default = defineTool3({
  name: "get_post",
  title: "Get post",
  description: "Fetch a WanaIQ post by id along with its top-level comments (most recent first).",
  inputSchema: {
    post_id: z2.string().uuid().describe("Post UUID."),
    comment_limit: z2.number().int().min(0).max(50).optional().describe("Max top-level comments to include (0-50, default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ post_id, comment_limit }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const { data: post, error: postErr } = await sb.from("posts").select(
      "id, title, content, author_id, community_id, upvotes, downvotes, comment_count, created_at, tags, link_url"
    ).eq("id", post_id).maybeSingle();
    if (postErr) return errorResult(postErr.message);
    if (!post) return errorResult("Post not found or not accessible.");
    const { data: comments, error: cErr } = await sb.from("comments").select("id, author_id, content, upvotes, downvotes, created_at, parent_comment_id").eq("post_id", post_id).is("parent_comment_id", null).eq("is_deleted", false).order("created_at", { ascending: false }).limit(comment_limit ?? 20);
    if (cErr) return errorResult(cErr.message);
    return jsonResult(
      { post, comments: comments ?? [] },
      `${post.title} \u2014 ${comments?.length ?? 0} top-level comment(s).`
    );
  }
});

// src/lib/mcp/tools/list-my-communities.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_communities_default = defineTool4({
  name: "list_my_communities",
  title: "List my communities",
  description: "List the WanaIQ communities the signed-in user has joined, most recently joined first.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("community_members").select(
      "joined_at, communities(id, name, display_name, description, category, member_count, type, visibility_type)"
    ).eq("user_id", ctx.getUserId()).order("joined_at", { ascending: false }).limit(50);
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], `${data?.length ?? 0} joined communities.`);
  }
});

// src/lib/mcp/tools/list-representatives.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_representatives_default = defineTool5({
  name: "list_representatives",
  title: "List representatives",
  description: "List verified office holders for a Kenyan county (defaults to the signed-in user's county). Returns active leaders with their office and profile info.",
  inputSchema: {
    county: z3.string().trim().min(1).optional().describe("Kenyan county name. Defaults to the signed-in user's county.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ county }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    let targetCounty = county;
    if (!targetCounty) {
      const { data: me } = await sb.from("profiles").select("county").eq("id", ctx.getUserId()).maybeSingle();
      targetCounty = me?.county ?? void 0;
    }
    if (!targetCounty) {
      return errorResult(
        "No county specified and the signed-in user has no county on their profile."
      );
    }
    const { data, error } = await sb.from("office_holders").select(
      "id, position_id, term_start, term_end, is_active, verification_status, profiles:user_id(id, username, display_name, avatar_url, county, constituency, ward, official_position)"
    ).eq("is_active", true).eq("verification_status", "verified").limit(100);
    if (error) return errorResult(error.message);
    const filtered = (data ?? []).filter((row) => {
      const p = row.profiles;
      return p && (p.county ?? "").toLowerCase() === targetCounty.toLowerCase();
    });
    return jsonResult(
      filtered,
      `${filtered.length} representative(s) for ${targetCounty}.`
    );
  }
});

// src/lib/mcp/tools/search-promises.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var search_promises_default = defineTool6({
  name: "search_promises",
  title: "Search campaign promises",
  description: "Search WanaIQ campaign promises by keyword and/or status. Returns up to 20 tracked promises.",
  inputSchema: {
    query: z4.string().trim().optional().describe("Search keywords matched against promise title and description."),
    status: z4.string().trim().optional().describe("Optional status filter (e.g. 'pending', 'in_progress', 'fulfilled', 'broken')."),
    limit: z4.number().int().min(1).max(20).optional().describe("Max results (1-20, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, status, limit }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    let q = sb.from("campaign_promises").select(
      "id, title, description, status, politician_id, politician_name, due_date, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    if (query && query.length > 0) {
      const term = `%${query.replace(/[%_]/g, "")}%`;
      q = q.or(`title.ilike.${term},description.ilike.${term}`);
    }
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], `${data?.length ?? 0} promise(s) found.`);
  }
});

// src/lib/mcp/tools/list-recent-posts.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_recent_posts_default = defineTool7({
  name: "list_recent_posts",
  title: "List recent posts",
  description: "List the most recent WanaIQ posts. Optionally scope to a community by id.",
  inputSchema: {
    community_id: z5.string().uuid().optional().describe("Optional community UUID to scope the feed."),
    limit: z5.number().int().min(1).max(25).optional().describe("Max results (1-25, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ community_id, limit }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    let q = sb.from("posts").select(
      "id, title, author_id, community_id, upvotes, downvotes, comment_count, created_at, tags"
    ).eq("is_hidden", false).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (community_id) q = q.eq("community_id", community_id);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], `${data?.length ?? 0} recent post(s).`);
  }
});

// src/lib/mcp/index.ts
var projectRef = "zcnjpczplkbdmmovlrtv";
var mcp_default = defineMcp({
  name: "wanaiq-mcp",
  title: "WanaIQ Civic",
  version: "0.1.0",
  instructions: "Read-only civic tools for WanaIQ (Kenya). Use whoami to identify the caller, search_posts to find civic discussions, get_post to fetch a post with its comments, list_my_communities for the user's communities, list_representatives for their elected leaders, search_promises to track campaign promises, and list_recent_posts for activity in the user's county. All calls run as the signed-in user under RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    search_posts_default,
    get_post_default,
    list_my_communities_default,
    list_representatives_default,
    search_promises_default,
    list_recent_posts_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
